# FILE OPEN MODES:
# r - read - DEFAULT VALUE. OPENS A FILE FOR READING.  ERROR IF THE FILE DOES NOT EXIST.
# w - write - OPENS A FILE FOR WRITING. CREATES A NEW FILE IF THE FILE DOES NOT EXIST.
# a - append - OPENS A FILE FOR APPENDING TO THE END. CREATES A NEW FILE IF THE FILE DOES NOT EXIST.
# x - create - CREATES A FILE. ERROR IF THE FILE EXISTS.
# + - read and write

